### PR TITLE
Changed z_index from 99/100 to 9998/9999 to bring overlay and menu to foreground

### PR DESCRIPTION
**Pull request by AlexLnz**
solves #34

### CODE REVIEW

**Comment by msarsha** [comment]
Thanks!

**Comment by msarsha** [comment]
closes #34

**Comment by AlexLnz** [comment]
Pleasure.
Should I have updated the CHANGELOG or do you maintain it personally?

**Comment by msarsha** [comment]
I will update the changelog.

Thanks again.

**Comment by AlexLnz** [comment]
OK, thank you.

**Pull request merged**
