### PR TITLE
Catch menus back to browser's window area

### PR DESCRIPTION
**Pull request by AlexLnz**
This is a first approach towards #4 .

### CODE REVIEW

**Comment by Hughp135** [comment]
After looking through your approach, I'm not sure if there is a need for a whole new service just for this functionality.

Is there a reason why you are overriding the position after view init, instead of setting the correct position in  `sh-context-menu-directive.ts` in the `setLocation` function?

**Comment by AlexLnz** [comment]
Hi Hughp135,

Thank you for reviewing the code. 

Yes, the code for positioning is in a separate class which does the job.
This follows the "single responsibility principle" of agile software design.

Regarding the second point it's not clear to me what you mean and how to save a lot of extra code. Could you elaborate on this?

regards,
Alex

**Comment by Hughp135** [comment]
After thinking it through it seems the way you have done it is good (as the problem was a bit more complex than I thought at first). Just need to get my local setup working so I can test it out a bit.

**Comment by Hughp135** [comment]
Have tested this and it seems to work well with LTR menus, but doesn't work for RTL menus.

Also need to merge in master (and move files from src/app to lib/src).

image

**Comment by msarsha** [comment]
implemented with #55 

Thanks @AlexLnz .

**Pull request closed without merging**
